# Generated by Django 4.2.30 on 2026-04-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_code", models.CharField(blank=True, max_length=15, unique=True)),
                ("intent", models.CharField(max_length=50)),
                ("entities", models.JSONField(default=dict)),
                ("generated_steps", models.JSONField(blank=True, default=list)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("employee_assignment", models.CharField(blank=True, max_length=50)),
                ("whatsapp_message", models.TextField(blank=True)),
                ("email_message", models.TextField(blank=True)),
                ("sms_message", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
